builds:
  - binary: envkey-fetch
    ldflags:
      - '-s -w'
      - '-extldflags "-static"'
    env:
      - CGO_ENABLED=0
      - GOROOT_FINAL=/usr/go
    goos:
      - darwin
      - linux
      - windows
      - freebsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7

